# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-dbd4493c-ae66-4542-8fdf-ebb5e5948e22";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-dbd4493c-ae66-4542-8fdf-ebb5e5948e22".device = "/dev/disk/by-uuid/dbd4493c-ae66-4542-8fdf-ebb5e5948e22";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7548-C528";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-588ac9fc-e3ba-4c6b-b963-b655ebedf967"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
