# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-intel" ];
    boot.extraModulePackages = [ ];

    fileSystems."/" =
      { device = "/dev/disk/by-uuid/b0f7d957-e024-4fdc-aca3-e0df0877376c";
      fsType = "ext4";
      };

      boot.initrd.luks.devices."luks-a2978bc4-a7d0-42ef-bf34-cf992ade1a90".device = "/dev/disk/by-uuid/a2978bc4-a7d0-42ef-bf34-cf992ade1a90";

      fileSystems."/boot" =
        { device = "/dev/disk/by-uuid/DF22-83CB";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
        };

        swapDevices =
          [ { device = "/dev/disk/by-uuid/024fce9d-4de3-4ba7-a108-037106b5179a"; }
          ];

          # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
          # (the default) this is the recommended approach. When using systemd-networkd it's
          # still possible to use this option, but it's recommended to use it in conjunction
          # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
          networking.useDHCP = lib.mkDefault true;
          # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

          nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
          hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
